-- Portable synthetic source: no files or pre-existing tables are required.
CREATE OR REFRESH MATERIALIZED VIEW bronze_patients (
  CONSTRAINT valid_pat_id EXPECT (PAT_ID IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_birth_date EXPECT (BIRTH_DATE IS NOT NULL)
)
COMMENT 'Synthetic Clarity-shaped PATIENT records generated by this pipeline.'
TBLPROPERTIES ('quality' = 'bronze')
AS
WITH patient_ids AS (
  SELECT CAST(id + 1 AS INT) AS n FROM range(200)
)
SELECT
  CONCAT('PAT', LPAD(CAST(n AS STRING), 5, '0')) AS PAT_ID,
  CONCAT('MRN', LPAD(CAST(n AS STRING), 8, '0')) AS PAT_MRN_ID,
  CASE WHEN pmod(n, 2) = 0 THEN 'Ms.' ELSE 'Mr.' END AS NAME_PREFIX,
  element_at(array('Alex', 'Jordan', 'Taylor', 'Morgan', 'Casey', 'Riley', 'Avery', 'Sam'), pmod(n, 8) + 1) AS PAT_FIRST_NAME,
  element_at(array('Lee', 'Patel', 'Garcia', 'Kim', 'Brown', 'Rivera', 'Nguyen', 'Davis'), pmod(n * 3, 8) + 1) AS PAT_LAST_NAME,
  CAST(NULL AS STRING) AS NAME_SUFFIX,
  CAST(NULL AS STRING) AS PAT_MAIDEN_NAME,
  CASE WHEN pmod(n, 3) = 0 THEN 'M' ELSE 'S' END AS MARITAL_STATUS_C,
  CASE WHEN pmod(n, 2) = 0 THEN 'F' ELSE 'M' END AS SEX_C,
  element_at(array('White', 'Black', 'Asian', 'Other'), pmod(n, 4) + 1) AS RACE_C,
  CASE WHEN pmod(n, 5) = 0 THEN 'Hispanic' ELSE 'Non-Hispanic' END AS ETHNIC_GROUP_C,
  date_add(DATE '1950-01-01', pmod(n * 137, 18000)) AS BIRTH_DATE,
  CASE WHEN pmod(n, 31) = 0 THEN DATE '2025-12-31' ELSE CAST(NULL AS DATE) END AS DEATH_DATE,
  CONCAT(CAST(n AS STRING), ' Demo Lane') AS ADD_LINE_1,
  element_at(array('Seattle', 'Chicago', 'Austin', 'Oakland'), pmod(n, 4) + 1) AS CITY,
  element_at(array('WA', 'IL', 'TX', 'CA'), pmod(n, 4) + 1) AS STATE_C,
  CAST(10000 + pmod(n * 17, 80000) AS STRING) AS ZIP,
  'Synthetic City' AS BIRTHPLACE,
  TIMESTAMP '2026-01-01 00:00:00' AS _LOAD_TIMESTAMP,
  'synthetic://patients' AS _SOURCE_FILE_PATH,
  TIMESTAMP '2026-01-01 00:00:00' AS ingested_at
FROM patient_ids;
