-- One diagnosis per encounter, with a mix of active and resolved records.
CREATE OR REFRESH MATERIALIZED VIEW bronze_diagnoses (
  CONSTRAINT valid_patient EXPECT (PAT_ID IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_dx_code EXPECT (DX_ID IS NOT NULL) ON VIOLATION DROP ROW
)
COMMENT 'Synthetic Clarity-shaped DIAGNOSIS records generated by this pipeline.'
TBLPROPERTIES ('quality' = 'bronze')
AS
WITH diagnosis_ids AS (
  SELECT
    CAST(id + 1 AS INT) AS n,
    CAST(floor(id / 2) + 1 AS INT) AS patient_n,
    date_add(DATE '2024-01-01', CAST(pmod(id * 3, 720) AS INT)) AS diagnosis_date,
    CASE pmod(id, 5)
      WHEN 0 THEN 44054006
      WHEN 1 THEN 38341003
      WHEN 2 THEN 195967001
      WHEN 3 THEN 21522001
      ELSE 84114007
    END AS diagnosis_code,
    CASE pmod(id, 5)
      WHEN 0 THEN 'Type 2 diabetes mellitus'
      WHEN 1 THEN 'Hypertension'
      WHEN 2 THEN 'Asthma'
      WHEN 3 THEN 'Abdominal pain'
      ELSE 'Heart failure'
    END AS diagnosis_name
  FROM range(400)
)
SELECT
  CAST(diagnosis_code AS BIGINT) AS DX_ID,
  CONCAT('PAT', LPAD(CAST(patient_n AS STRING), 5, '0')) AS PAT_ID,
  CONCAT('ENC', LPAD(CAST(n AS STRING), 6, '0')) AS PAT_ENC_CSN_ID,
  diagnosis_name AS REF_BILL_CODE_NAME,
  diagnosis_date AS DX_DATE,
  CASE WHEN pmod(n, 4) = 0 THEN date_add(diagnosis_date, 14)
       ELSE CAST(NULL AS DATE) END AS RESOLVED_DATE,
  TIMESTAMP '2026-01-01 00:00:00' AS _LOAD_TIMESTAMP,
  'synthetic://diagnoses' AS _SOURCE_FILE_PATH,
  TIMESTAMP '2026-01-01 00:00:00' AS ingested_at
FROM diagnosis_ids;
