-- Two deterministic encounters per synthetic patient.
CREATE OR REFRESH MATERIALIZED VIEW bronze_encounters (
  CONSTRAINT valid_csn EXPECT (PAT_ENC_CSN_ID IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_patient EXPECT (PAT_ID IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_contact_date EXPECT (CONTACT_DATE IS NOT NULL)
)
COMMENT 'Synthetic Clarity-shaped PAT_ENC records generated by this pipeline.'
TBLPROPERTIES ('quality' = 'bronze')
AS
WITH encounter_ids AS (
  SELECT
    CAST(id + 1 AS INT) AS n,
    CAST(floor(id / 2) + 1 AS INT) AS patient_n,
    timestampadd(DAY, CAST(pmod(id * 3, 720) AS INT), TIMESTAMP '2024-01-01 08:00:00') AS contact_date,
    CASE pmod(id, 5)
      WHEN 0 THEN 44054006
      WHEN 1 THEN 38341003
      WHEN 2 THEN 195967001
      WHEN 3 THEN 21522001
      ELSE 84114007
    END AS diagnosis_code,
    CASE pmod(id, 5)
      WHEN 0 THEN 'Type 2 diabetes mellitus'
      WHEN 1 THEN 'Hypertension'
      WHEN 2 THEN 'Asthma'
      WHEN 3 THEN 'Abdominal pain'
      ELSE 'Heart failure'
    END AS diagnosis_name
  FROM range(400)
)
SELECT
  CONCAT('ENC', LPAD(CAST(n AS STRING), 6, '0')) AS PAT_ENC_CSN_ID,
  CONCAT('PAT', LPAD(CAST(patient_n AS STRING), 5, '0')) AS PAT_ID,
  CONCAT('PROV', LPAD(CAST(pmod(n, 20) + 1 AS STRING), 3, '0')) AS VISIT_PROV_ID,
  CASE WHEN pmod(n, 5) = 0 THEN 'inpatient'
       WHEN pmod(n, 5) = 1 THEN 'emergency'
       ELSE 'ambulatory' END AS ENC_TYPE_C,
  diagnosis_code AS ENC_REASON_CODE,
  CONCAT('Encounter for ', diagnosis_name) AS ENC_REASON_DESC,
  diagnosis_code AS DX_PRIMARY_CODE,
  diagnosis_name AS DX_PRIMARY_DESC,
  contact_date AS CONTACT_DATE,
  timestampadd(HOUR, CASE WHEN pmod(n, 5) = 0 THEN 48
                          WHEN pmod(n, 5) = 1 THEN 8
                          ELSE 1 END, contact_date) AS ENC_END_DATE,
  CAST(75 + pmod(n * 137, 5000) AS DECIMAL(12,2)) AS ENC_TOT_CHG,
  TIMESTAMP '2026-01-01 00:00:00' AS _LOAD_TIMESTAMP,
  'synthetic://encounters' AS _SOURCE_FILE_PATH,
  TIMESTAMP '2026-01-01 00:00:00' AS ingested_at
FROM encounter_ids;
